server:
  port: 3333

spring:
  data:
    maria:
      jdbc-url: jdbc:mariadb://3.36.127.118:3306/NorisWebDB
      driver-class-name: org.mariadb.jdbc.Driver
      username: connection
      password: 1234
  jpa:
    properties:
      hibernate:
        #show_sql: true
        ddl-auto: create-drop
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
