server:
  port: 3333

spring:
  data:
    maria:
      jdbc-url: jdbc:mariadb://localhost:3306/software_project
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: yoon8863
  jpa:
    properties:
      hibernate:
        #show_sql: true
        ddl-auto: create-drop
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
